name: Changesets
on:
  push:
    branches:
      - main
      - prerelease/*
jobs:
  changesets:
    name: Changesets
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set Up NodeJS
        uses: actions/setup-node@v2
        with:
          always-auth: true
          cache: yarn
          node-version: 14
          registry-url: "https://npm.pkg.github.com"
      - name: Install Node Modules
        run: yarn install --frozen-lockfile
      - name: Changesets
        uses: changesets/action@master
        if: ${{ !env.ACT }}
        with:
          commit: Publish New Version
          title: Publish New Version
          publish: yarn package:publish
          version: yarn package:version
        env:
          GITHUB_TOKEN: ${{ GITHUB.TOKEN }}
          NODE_AUTH_TOKEN: ${{ GITHUB.TOKEN }}
