name: Changesets
on:
  push:
    branches:
      - main
jobs:
  changesets:
    name: Changesets
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set Up NodeJS
        uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: 14
          registry-url: "https://npm.pkg.github.com"
      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-modules-
      - name: Install Node Modules
        run: yarn install --frozen-lockfile
      - name: Changesets
        uses: changesets/action@master
        with:
          commit: Publish New Version
          title: Publish New Version
          publish: yarn changeset:publish
          version: yarn changeset:version
        env:
          GITHUB_TOKEN: ${{ GITHUB.TOKEN }}
          NODE_AUTH_TOKEN: ${{ GITHUB.TOKEN }}
